import { Attendee, Booking, EventItem, TicketType } from './types'

const IMG = {
  concert: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&q=80&auto=format&fit=crop',
  workshop: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80&auto=format&fit=crop',
  jam: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&q=80&auto=format&fit=crop',
  paint: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&q=80&auto=format&fit=crop',
  extra1: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80&auto=format&fit=crop',
  extra2: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=800&q=80&auto=format&fit=crop',
}

const AVATAR = 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&q=80&auto=format&fit=crop'

const tt = (o: Partial<TicketType> & { id: string; name: string; price: number; quantity: number }): TicketType => ({
  currency: 'INR', sold: 0, salesStart: '2026-07-01', salesEnd: '2026-08-17',
  maxPerBuyer: 6, description: '', benefits: '', refundable: true, ...o,
})

const HOME = {
  ragas: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800&q=80&auto=format&fit=crop',
  canvas: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&q=80&auto=format&fit=crop',
  rhythm: 'https://images.unsplash.com/photo-1543443258-92b04ad5ec6b?w=800&q=80&auto=format&fit=crop',
  coast: 'https://images.unsplash.com/photo-1552168324-d612d77725e3?w=800&q=80&auto=format&fit=crop',
}

export const seedEvents: EventItem[] = [
  // ---- Home "Upcoming Events" (same canonical source as Details/Tickets/Checkout) ----
  {
    id: 'ragas-of-dusk',
    title: 'Ragas of Dusk',
    category: 'In-door Baithak',
    summary: 'An intimate evening of twilight ragas on sitar, accompanied by tabla and tanpura.',
    description:
      'An intimate evening of twilight ragas on sitar, accompanied by tabla and tanpura. Kabir Menon leads a contemplative recital of evening ragas performed in the round at the NCPA.',
    format: 'In person', language: 'Hindustani', audience: 'All ages',
    tags: ['Hindustani', 'Sitar', 'Recital'],
    performers: [
      { id: 'p1', name: 'Kabir Menon', role: 'Sitar' },
      { id: 'p2', name: 'Devraj Singh', role: 'Tabla' },
    ],
    expect: 'A seated recital of twilight ragas across roughly two and a half hours, with a short interval.',
    startDate: '2026-07-28', startTime: '18:30', endDate: '2026-07-28', endTime: '21:00',
    timezone: 'IST (GMT+5:30)', multiDay: false, recurring: false,
    regClose: '2026-07-28T17:00', doorTime: '18:00',
    schedule: [
      { id: 's1', start: '18:00', end: '18:30', title: 'Doors open & seating', host: 'NCPA', description: 'Seating opens.' },
      { id: 's2', start: '18:30', end: '21:00', title: 'Recital — Ragas of Dusk', host: 'Kabir Menon', description: 'Twilight ragas on sitar with tabla and tanpura.' },
    ],
    venueName: 'NCPA', address: 'Nariman Point', city: 'Mumbai', state: 'Maharashtra', country: 'India', postal: '400021',
    venueInstructions: 'Carry a valid ID. Latecomers seated during the interval.',
    accessibility: 'Wheelchair accessible. Accessible restrooms available.',
    parking: 'Paid parking available at NCPA.',
    paid: true,
    tickets: [
      tt({ id: 't-ga', name: 'General Admission', price: 799, quantity: 80, description: 'Open seating.', benefits: 'Event entry', maxPerBuyer: 4 }),
      tt({ id: 't-prem', name: 'Premium Seating', price: 1299, quantity: 30, description: 'Reserved front-block seating.', benefits: 'Reserved seat', maxPerBuyer: 4 }),
    ],
    capacity: 110, waitlist: true, approvalRequired: false, maxPerPerson: 4,
    refundPolicy: 'Refundable up to 48 hours before the event. A 10% processing fee applies.',
    cover: HOME.ragas, images: [HOME.ragas], accent: '#9D2567', featured: true,
    organiserId: 'kabir-menon', organiserName: 'Kabir Menon', organiserAvatar: AVATAR,
    status: 'published',
  },
  {
    id: 'canvas-open-studio',
    title: 'Canvas: Open Studio',
    category: 'Painting Session',
    summary: 'Wander through open studios and meet painters mid-process. Free entry, all welcome.',
    description: 'A free, walk-through open studio in the Indiranagar art district. Meet painters at work, ask questions and watch pieces take shape across the afternoon.',
    format: 'In person', language: 'English', audience: 'All ages', tags: ['Open Studio', 'Painting'],
    performers: [{ id: 'p1', name: 'Meera Iyer', role: 'Host artist' }],
    expect: 'A self-paced walk-through of working studios with informal artist chats.',
    startDate: '2026-08-02', startTime: '11:00', endDate: '2026-08-02', endTime: '17:00',
    timezone: 'IST (GMT+5:30)', multiDay: false, recurring: false, regClose: '2026-08-02T10:00', doorTime: '11:00',
    schedule: [],
    venueName: 'Indiranagar Art District', address: '100 Ft Road, Indiranagar', city: 'Bengaluru', state: 'Karnataka', country: 'India', postal: '560038',
    accessibility: 'Ground-floor studios are wheelchair accessible.', parking: 'Street parking nearby.',
    paid: false, tickets: [], capacity: 200, waitlist: false, approvalRequired: false, maxPerPerson: 4,
    refundPolicy: '', cover: HOME.canvas, images: [HOME.canvas], accent: '#9D2567',
    organiserId: 'meera-iyer', organiserName: 'Meera Iyer', organiserAvatar: AVATAR, status: 'published',
  },
  {
    id: 'rhythm-lab',
    title: 'Rhythm Lab: Tabla Intensive',
    category: 'Workshop',
    summary: 'A hands-on masterclass on Jaipur gharana compositions for intermediate players.',
    description: 'An intensive tabla masterclass focused on Jaipur gharana compositions. Bring your own tabla; intermediate playing level recommended.',
    format: 'In person', language: 'Hindi, English', audience: 'Intermediate', tags: ['Tabla', 'Workshop', 'Hindustani'],
    performers: [{ id: 'p1', name: 'Devraj Singh', role: 'Instructor' }],
    expect: 'A three-hour intensive with demonstration, guided practice and Q&A.',
    startDate: '2026-08-09', startTime: '10:00', endDate: '2026-08-09', endTime: '13:00',
    timezone: 'IST (GMT+5:30)', multiDay: false, recurring: false, regClose: '2026-08-09T09:00', doorTime: '09:30',
    schedule: [],
    venueName: 'Jawahar Kala Kendra', address: 'Jawahar Lal Nehru Marg', city: 'Jaipur', state: 'Rajasthan', country: 'India', postal: '302004',
    accessibility: 'Wheelchair accessible.', parking: 'On-site parking.',
    paid: true,
    tickets: [tt({ id: 't-ws', name: 'Workshop Pass', price: 1200, quantity: 25, description: 'Full workshop access.', benefits: 'Materials included', maxPerBuyer: 2 })],
    capacity: 25, waitlist: true, approvalRequired: false, maxPerPerson: 2,
    refundPolicy: 'Refundable up to 72 hours before the workshop.', cover: HOME.rhythm, images: [HOME.rhythm], accent: '#9D2567',
    organiserId: 'devraj-singh', organiserName: 'Devraj Singh', organiserAvatar: AVATAR, status: 'published',
  },
  {
    id: 'coastal-frames',
    title: 'Coastal Frames',
    category: 'Others',
    summary: 'A free exhibition documenting the fishing and craft communities of the Malabar coast.',
    description: 'A free photo exhibition documenting the fishing and craft communities of the Malabar coast, on view at the Fort Kochi Pavilion.',
    format: 'In person', language: 'English', audience: 'All ages', tags: ['Photography', 'Exhibition'],
    performers: [{ id: 'p1', name: 'Nisha Pillai', role: 'Photographer' }],
    expect: 'A self-guided exhibition with printed notes on each series.',
    startDate: '2026-08-15', startTime: '10:00', endDate: '2026-08-15', endTime: '18:00',
    timezone: 'IST (GMT+5:30)', multiDay: false, recurring: false, regClose: '2026-08-15T09:00', doorTime: '10:00',
    schedule: [],
    venueName: 'Fort Kochi Pavilion', address: 'Fort Kochi', city: 'Kochi', state: 'Kerala', country: 'India', postal: '682001',
    accessibility: 'Wheelchair accessible.', parking: 'Public parking nearby.',
    paid: false, tickets: [], capacity: 300, waitlist: false, approvalRequired: false, maxPerPerson: 4,
    refundPolicy: '', cover: HOME.coast, images: [HOME.coast], accent: '#9D2567',
    organiserId: 'nisha-pillai', organiserName: 'Nisha Pillai', organiserAvatar: AVATAR, status: 'published',
  },
  {
    id: 'echoes-of-ujjain',
    title: 'Echoes of Ujjain',
    category: 'Concert',
    summary: 'A live concert of original fusion compositions under the Mumbai sky.',
    description:
      'Abhishek Singh Chouhan brings his signature blend of Hindustani classical and contemporary production to the stage for one unforgettable night. Expect original compositions, live improvisation and a full band.',
    format: 'In person',
    language: 'Hindi, English',
    audience: 'All ages',
    tags: ['Fusion', 'Live Band', 'Original Music'],
    performers: [
      { id: 'p1', name: 'Abhishek Singh Chouhan', role: 'Composer & Vocals' },
      { id: 'p2', name: 'Kabir Menon', role: 'Sitar' },
    ],
    expect: 'A 2-hour live set with an opening act, original songs and an interactive encore.',
    startDate: '2026-08-18', startTime: '20:00', endDate: '2026-08-18', endTime: '22:30',
    timezone: 'IST (GMT+5:30)', multiDay: false, recurring: false,
    regClose: '2026-08-18T18:00', doorTime: '19:15',
    schedule: [
      { id: 's1', start: '19:15', end: '20:00', title: 'Doors open & opening act', host: 'The Loft Collective', description: 'Warm-up set and seating.' },
      { id: 's2', start: '20:00', end: '21:30', title: 'Main performance', host: 'Abhishek Singh Chouhan', description: 'Original compositions.' },
      { id: 's3', start: '21:30', end: '22:30', title: 'Encore & meet', host: 'Abhishek Singh Chouhan', description: 'Interactive encore.' },
    ],
    venueName: 'antiSOCIAL, Hauz Khas', address: 'Hauz Khas Village', city: 'Delhi',
    state: 'Maharashtra', country: 'India', postal: '400052',
    venueInstructions: 'Entry from Gate 2. Carry a valid ID.',
    accessibility: 'Wheelchair accessible. Accessible restrooms available.',
    parking: 'Paid parking available at Rohan Plaza.',
    paid: true,
    tickets: [
      tt({ id: 't-eb', name: 'Early Bird', price: 399, quantity: 60, sold: 54, description: 'Limited early-bird pricing.', benefits: 'Priority entry', maxPerBuyer: 4 }),
      tt({ id: 't-ga', name: 'General Admission', price: 599, quantity: 200, sold: 120, description: 'Standing / open seating.', benefits: 'Event entry' }),
      tt({ id: 't-vip', name: 'VIP', price: 1499, quantity: 30, sold: 12, description: 'Front rows + meet & greet.', benefits: 'Reserved seat, meet & greet, merch', maxPerBuyer: 2 }),
    ],
    capacity: 290, waitlist: true, approvalRequired: false, maxPerPerson: 6,
    refundPolicy: 'Refundable up to 48 hours before the event. A 10% processing fee applies.',
    cover: IMG.concert, images: [IMG.concert, IMG.extra1], accent: '#9D2567', featured: true,
    organiserId: 'abhishek-singh-chouhan', organiserName: 'Abhishek Singh Chouhan', organiserAvatar: AVATAR,
    status: 'published',
  },
  {
    id: 'intro-classical-composition',
    title: 'Introduction to Indian Classical Composition',
    category: 'Workshop',
    summary: 'A free online workshop on the fundamentals of composing in the classical tradition.',
    description:
      'A beginner-friendly session covering raga basics, structure and simple composition exercises. Bring an instrument or just your ears. Hosted live online.',
    format: 'Online',
    language: 'Hindi, English',
    audience: 'Beginners',
    tags: ['Composition', 'Theory', 'Beginner'],
    performers: [{ id: 'p1', name: 'Abhishek Singh Chouhan', role: 'Instructor' }],
    expect: 'A 90-minute interactive session with a live Q&A.',
    startDate: '2026-08-24', startTime: '11:00', endDate: '2026-08-24', endTime: '12:30',
    timezone: 'IST (GMT+5:30)', multiDay: false, recurring: false,
    regClose: '2026-08-24T10:00', doorTime: '',
    schedule: [
      { id: 's1', start: '11:00', end: '11:45', title: 'Fundamentals', host: 'Abhishek Singh Chouhan', description: 'Raga & structure.' },
      { id: 's2', start: '11:45', end: '12:30', title: 'Composition exercise + Q&A', host: 'Abhishek Singh Chouhan', description: 'Hands-on.' },
    ],
    online: { platform: 'Zoom', link: 'https://zoom.us/j/prototype-echoes', instructions: 'Join 5 minutes early. Link revealed after registration.' },
    paid: false,
    tickets: [],
    capacity: 100, waitlist: true, approvalRequired: false, maxPerPerson: 2,
    refundPolicy: 'Free event — cancel anytime.',
    cover: IMG.workshop, images: [IMG.workshop], accent: '#227A52',
    organiserId: 'abhishek-singh-chouhan', organiserName: 'Abhishek Singh Chouhan', organiserAvatar: AVATAR,
    status: 'published',
  },
  {
    id: 'sunday-indie-jam',
    title: 'Sunday Indie Music Jam',
    category: 'Music Jam',
    summary: 'An open, limited-capacity jam for indie musicians and listeners.',
    description:
      'Bring your instrument and join a relaxed Sunday afternoon jam. Limited spots to keep it intimate. Listeners welcome too.',
    format: 'In person',
    language: 'English',
    audience: 'Musicians & listeners',
    tags: ['Indie', 'Open Mic', 'Community'],
    performers: [{ id: 'p1', name: 'Bengaluru Indie Collective', role: 'Hosts' }],
    expect: 'A rotating open jam with a house kit and PA.',
    startDate: '2026-08-30', startTime: '16:00', endDate: '2026-08-30', endTime: '19:00',
    timezone: 'IST (GMT+5:30)', multiDay: false, recurring: false,
    regClose: '2026-08-30T14:00', doorTime: '15:45',
    schedule: [],
    venueName: 'The Courtyard', address: 'Indiranagar 100ft Rd', city: 'Bengaluru',
    state: 'Karnataka', country: 'India', postal: '560038',
    venueInstructions: 'Limited seating. First come, first served.',
    accessibility: 'Ground floor, step-free entry.',
    parking: 'Street parking only.',
    paid: false,
    tickets: [],
    capacity: 30, waitlist: true, approvalRequired: true, maxPerPerson: 2,
    refundPolicy: 'Free event.',
    cover: IMG.jam, images: [IMG.jam], accent: '#B77818',
    organiserId: 'bengaluru-indie', organiserName: 'Bengaluru Indie Collective',
    status: 'published',
  },
  {
    id: 'colours-of-folk-art',
    title: 'Colours of Indian Folk Art',
    category: 'Painting Session',
    summary: 'A hands-on folk-art painting session in the heart of Jaipur.',
    description:
      'Learn the motifs and techniques of Indian folk art in a guided painting session. All materials provided. Take your canvas home.',
    format: 'In person',
    language: 'Hindi, English',
    audience: 'All levels',
    tags: ['Folk Art', 'Hands-on', 'Materials Included'],
    performers: [{ id: 'p1', name: 'Meera Iyer', role: 'Artist & Guide' }],
    expect: 'A 3-hour guided session; all materials included.',
    startDate: '2026-09-06', startTime: '10:30', endDate: '2026-09-06', endTime: '13:30',
    timezone: 'IST (GMT+5:30)', multiDay: false, recurring: false,
    regClose: '2026-09-05T20:00', doorTime: '10:15',
    schedule: [],
    venueName: 'Jaipur Art House', address: 'Civil Lines', city: 'Jaipur',
    state: 'Rajasthan', country: 'India', postal: '302006',
    venueInstructions: 'Wear clothes you don’t mind getting paint on.',
    accessibility: 'Accessible entrance available.',
    parking: 'Free on-site parking.',
    paid: true,
    tickets: [
      tt({ id: 't-ga', name: 'General Admission', price: 899, quantity: 25, sold: 8, description: 'Includes all materials.', benefits: 'Canvas, paints, guidance' }),
      tt({ id: 't-duo', name: 'Duo Pass', price: 1599, quantity: 10, sold: 3, description: 'For two people.', benefits: 'Two kits, shared table', maxPerBuyer: 3 }),
    ],
    capacity: 45, waitlist: false, approvalRequired: false, maxPerPerson: 4,
    refundPolicy: 'Refundable up to 24 hours before the session.',
    cover: IMG.paint, images: [IMG.paint, IMG.extra2], accent: '#592049',
    organiserId: 'meera-iyer', organiserName: 'Meera Iyer',
    status: 'published',
  },
]

// A couple of seed bookings for the demo "My Tickets" experience.
export const seedBookings: Booking[] = [
  {
    id: 'bk-seed-1', orderId: 'IICA-90231', eventId: 'echoes-of-ujjain',
    eventTitle: 'Echoes of Ujjain', eventDate: '2026-08-18', cover: IMG.concert, format: 'In person',
    status: 'Confirmed', qty: 2, ticketTypeName: 'General Admission', amount: 1198, paid: true,
    buyerName: 'Reshma Patra', buyerEmail: 'reshma@example.com', createdAt: '2026-07-20',
    tickets: [
      { id: 'tk-1', eventId: 'echoes-of-ujjain', ticketType: 'General Admission', attendeeName: 'Reshma Patra' },
      { id: 'tk-2', eventId: 'echoes-of-ujjain', ticketType: 'General Admission', attendeeName: 'Guest' },
    ],
  },
]

export const seedAttendees: Attendee[] = [
  { id: 'at1', eventId: 'echoes-of-ujjain', name: 'Reshma Patra', email: 'reshma@example.com', ticketType: 'General Admission', qty: 2, regDate: '2026-07-20', paymentStatus: 'Paid', checkedIn: false, approval: 'Confirmed' },
  { id: 'at2', eventId: 'echoes-of-ujjain', name: 'Vikram Joshi', email: 'vikram@example.com', ticketType: 'VIP', qty: 1, regDate: '2026-07-19', paymentStatus: 'Paid', checkedIn: true, approval: 'Confirmed' },
  { id: 'at3', eventId: 'echoes-of-ujjain', name: 'Sneha Rao', email: 'sneha@example.com', ticketType: 'Early Bird', qty: 2, regDate: '2026-07-15', paymentStatus: 'Paid', checkedIn: false, approval: 'Confirmed' },
  { id: 'at4', eventId: 'sunday-indie-jam', name: 'Arjun Desai', email: 'arjun@example.com', ticketType: 'Free', qty: 1, regDate: '2026-08-01', paymentStatus: 'Free', checkedIn: false, approval: 'Pending Approval' },
  { id: 'at5', eventId: 'sunday-indie-jam', name: 'Nisha Pillai', email: 'nisha@example.com', ticketType: 'Free', qty: 2, regDate: '2026-08-02', paymentStatus: 'Free', checkedIn: false, approval: 'Waitlisted' },
]

export const emptyDraftTicket = (): TicketType => tt({ id: 'nt', name: '', price: 0, quantity: 50 })
